### ISSUE TITLE
transmisson's configuration file not editable

### ISSUE THREAD

**Issue by oshino29** [codysk/bgmi-docker-all-in-one#2]
my docker-compose file looks like this:
```
services:
  bgmi:
    image: codysk/bgmi-all-in-one
    ports:
      - "29880:80"
      - "29091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./bangumi:/bgmi/bangumi
      - ./conf:/bgmi/conf
      - ./log:/bgmi/log
```   

bgmi and transmission worked fine together, the only issue is with the transmission web client.
when connectiong transmission rpc client via http://mydomain.com:29880 my browser will return a 403 page:
```
403: Forbidden
Unauthorized IP Address.

Either disable the IP address whitelist or add your address to it.

If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.

If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.
```
so I tried logging into the bgmi container and setting `rpc-whitelist-enabled = false` in `/bgmi/conf/transmission/settings.json`,  restarting my container
everytime the `settings.json` will be recovered to the initial state and blocked my access out of its whitelist `"127.0.0.1"`which only accept local connection.
